#ifndef WEBSERVER_H
#define WEBSERVER_H

// HTML page for BLE scanner web UI
const char HTML_PAGE[] = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<meta name='theme-color' content='#0f172a'>"
"<link rel='manifest' href='/manifest.json'>"
"<link rel='icon' type='image/png' sizes='192x192' href='/icon-192.png'>"
"<link rel='apple-touch-icon' sizes='192x192' href='/icon-192.png'>"
"<title>Temperatures</title>"
"<script src='https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'></script>"
"<script src='https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0/dist/chartjs-adapter-date-fns.bundle.min.js'></script>"
"<script>if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(r=>{r.update();}).catch(()=>{});});}</script>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
":root{--bg:#0b1222;--surface:#111a2e;--surface-2:#0f172a;--card:#121c32;--border:#26324a;"
"--text:#e5edf9;--muted:#9aa7bd;--accent:#4f9cff;--accent-2:#34d399;--shadow:0 10px 30px rgba(2,8,23,0.45)}"
"body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:radial-gradient(1200px 600px at 20% -10%,#18264a 0%,#0b1222 45%,#0a0f1b 100%);"
"min-height:100vh;padding:24px;color:var(--text)}"
".container{max-width:1040px;margin:0 auto}"
".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;"
"padding:12px 16px;background:linear-gradient(135deg,#152341 0%,#1c2b52 100%);"
"border-radius:14px;border:1px solid #223150;box-shadow:var(--shadow)}"
"h1{color:var(--text);font-size:20px;margin:0;font-weight:700;letter-spacing:-0.2px;"
"display:flex;align-items:center;gap:8px}"
".footer{margin-top:16px;text-align:center;color:#94a3b8;font-size:11px;"
"line-height:1.4}"
"body.compact-view .footer{display:none}"
".footer a{color:#94a3b8;text-decoration:none}"
".footer a:hover{text-decoration:underline}"
".toggle-btn{background:rgba(255,255,255,0.04);color:var(--text);border:1px solid #2a3a5c;"
"padding:10px 18px;border-radius:10px;cursor:pointer;font-size:13px;font-weight:600;"
"transition:all 0.2s;box-shadow:0 2px 10px rgba(2,8,23,0.3)}"
".toggle-btn:hover{background:rgba(255,255,255,0.08);border-color:#3a4d75;transform:translateY(-1px)}"
".toggle-btn.active{background:linear-gradient(135deg,#3b82f6,#60a5fa);border-color:#60a5fa;color:white}"
".toggle-btn.icon-btn{padding:8px;width:38px;height:38px;display:inline-flex;align-items:center;justify-content:center;font-size:18px}"
".time-btn{background:#16213a;color:var(--text);border:1px solid #2a3a5c;"
"padding:8px 16px;border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;"
"transition:all 0.2s;flex:1}"
".time-btn:hover{background:#1b2a4b;border-color:#3a4d75}"
".time-btn.active{background:linear-gradient(135deg,#3b82f6,#60a5fa);border-color:#60a5fa;color:white}"
".device-card{background:linear-gradient(180deg,#111a2e 0%,#0f172a 100%);"
"border:1px solid var(--border);border-radius:16px;padding:14px;"
"margin-bottom:10px;box-shadow:var(--shadow);position:relative;transition:all 0.2s;z-index:1}"
".device-card.compact{padding:12px}"
".device-card.settings-open{z-index:100}"
".device-card:hover{border-color:#3a4d75;transform:translateY(-2px)}"
".device-card.unsaved{border:2px dashed var(--accent-2);background:#0d2a24}"
".device-card.unsaved .device-name::after{content:' (unsaved)';font-size:12px;color:var(--accent-2);font-weight:500}"
".device-header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}"
".device-header-actions{display:flex;gap:6px;align-items:center}"
".device-info{flex:1}"
".device-name{font-size:18px;font-weight:700;color:var(--text);margin-bottom:4px;letter-spacing:-0.2px}"
".device-meta{font-size:12px;color:#94a3b8;margin-top:2px;display:flex;gap:8px;flex-wrap:wrap}"
".device-mac{font-family:'JetBrains Mono','Courier New',monospace;font-size:12px;color:var(--muted);"
"background:rgba(255,255,255,0.03);padding:4px 8px;border-radius:6px;display:inline-block;margin-top:4px;border:1px solid #223150}"
".expand-btn{background:#1b2a4b;border:1px solid #2a3a5c;color:#cfe0ff;border-radius:8px;"
"width:34px;height:34px;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;"
"font-size:14px;transition:all 0.2s}"
".expand-btn:hover{background:#23345a;border-color:#3a4d75}"
".compact-row{display:grid;grid-template-columns:1fr 1fr;gap:3px;margin-top:2px;"
"padding:6px 8px;background:#0d162a;border:1px solid #1c2a45;border-radius:10px}"
".compact-item{display:flex;align-items:baseline;gap:8px;font-weight:700;color:#cfe0ff;font-size:18px;"
"min-width:0}"
".compact-label{font-size:11px;color:#7f8aa3;letter-spacing:0.6px;text-transform:uppercase}"
".compact-age{font-weight:600;color:#94a3b8;margin-left:6px;font-size:10px;text-transform:none;letter-spacing:0}"
".device-card.compact .sensor-data{display:none}"
".device-card.compact .rssi{display:none}"
".device-card.compact .device-mac{display:none}"
".device-card.compact .device-header-actions{display:none}"
".device-card.compact.active-controls .device-header-actions{display:flex}"
".device-card:not(.compact) .compact-row{display:none}"
"body.compact-view #diagnostics{display:none}"
".settings-icon{background:none;border:none;font-size:24px;cursor:pointer;padding:8px;"
"color:#64748b;transition:all 0.2s;border-radius:8px}"
".settings-icon:hover{color:#e2e8f0;background:#334155;transform:rotate(90deg)}"
".settings-panel{display:none;position:absolute;right:16px;top:60px;background:#1e293b;"
"border:1px solid #334155;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,0.5);"
"min-width:240px;z-index:9999}"
".settings-panel.open{display:block}"
".settings-option{padding:12px 16px;cursor:pointer;transition:background 0.2s;"
"border-bottom:1px solid #334155;color:#e2e8f0}"
".settings-option:last-child{border-bottom:none}"
".settings-option:hover{background:#334155}"
".settings-option.danger{color:#f87171}"
".settings-option.danger:hover{background:#450a0a;color:#fca5a5}"
".danger-btn{background:#dc2626;color:white;border:none;padding:10px 14px;border-radius:8px;cursor:pointer;font-weight:700;transition:all 0.2s}"
".danger-btn:hover{background:#b91c1c;transform:translateY(-1px)}"
".sensor-data{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));"
"gap:12px;margin-top:16px;padding-top:16px;border-top:1px solid #334155}"
".sensor-value{text-align:center;background:#0f172a;padding:12px;border-radius:8px;"
"border:1px solid #1e293b;transition:all 0.2s}"
".sensor-value:hover{border-color:#334155;transform:translateY(-1px)}"
".sensor-value.primary{grid-column:span 1;background:linear-gradient(135deg,#1e293b,#334155);"
"border:2px solid #3b82f6;padding:16px}"
".sensor-label{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;"
"margin-bottom:8px;font-weight:600}"
".sensor-value.primary .sensor-label{font-size:12px;color:#60a5fa;font-weight:700}"
".sensor-number{font-size:22px;font-weight:700;color:#3b82f6}"
".sensor-value.primary .sensor-number{font-size:34px;color:#60a5fa;text-shadow:0 0 20px rgba(96,165,250,0.3)}"
".sensor-unit{font-size:12px;color:#64748b;margin-left:2px;font-weight:500}"
".sensor-value.primary .sensor-unit{font-size:16px;color:#93c5fd}"
".temp-cold{color:#60a5fa !important}"
".temp-cool{color:#34d399 !important}"
".temp-normal{color:#fbbf24 !important}"
".temp-warm{color:#fb923c !important}"
".temp-hot{color:#f87171 !important}"
".battery-container{display:flex;flex-direction:column;align-items:center;gap:8px}"
".battery-bar{width:80px;height:22px;border:2px solid #475569;border-radius:6px;position:relative;"
"background:#0f172a;overflow:hidden}"
".battery-bar::after{content:'';position:absolute;top:50%;right:-7px;transform:translateY(-50%);"
"width:4px;height:12px;background:#475569;border-radius:0 3px 3px 0}"
".battery-fill{height:100%;border-radius:3px;transition:width 0.3s,background 0.3s}"
".battery-fill.high{background:linear-gradient(90deg,#10b981,#34d399)}"
".battery-fill.medium{background:linear-gradient(90deg,#f59e0b,#fbbf24)}"
".battery-fill.low{background:linear-gradient(90deg,#ef4444,#f87171)}"
".signal-container{display:flex;align-items:center;gap:8px;justify-content:center}"
".signal-bars{display:flex;align-items:flex-end;gap:3px;height:20px}"
".signal-bar{width:5px;border-radius:2px;transition:background 0.3s}"
".signal-bar:nth-child(1){height:25%}"
".signal-bar:nth-child(2){height:50%}"
".signal-bar:nth-child(3){height:75%}"
".signal-bar:nth-child(4){height:100%}"
".signal-bar.active.excellent,.signal-bar.active.good{background:#10b981}"
".signal-bar.active.fair{background:#f59e0b}"
".signal-bar.active.poor{background:#ef4444}"
".signal-bar.inactive{background:#334155}"
".rssi{display:inline-block;margin-top:12px;padding:6px 12px;background:#0f172a;"
"border-radius:6px;font-size:12px;color:#94a3b8;border:1px solid #1e293b}"
".chart-container{margin-top:20px;padding-top:20px;border-top:1px solid #334155;height:200px;position:relative}"
".chart-container canvas{max-height:180px}"
".chart-latest{display:flex;align-items:center;gap:12px;background:#0f172a;border:1px solid #1e293b;"
"border-radius:10px;padding:10px 12px;margin-bottom:12px;color:#e2e8f0}"
".chart-latest .label{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;font-weight:700}"
".chart-latest .value{font-size:24px;font-weight:800;color:#f1f5f9}"
".chart-latest .unit{font-size:12px;color:#94a3b8;margin-left:4px;font-weight:600}"
".chart-latest .meta{margin-left:auto;font-size:12px;color:#94a3b8}"
".no-devices{text-align:center;padding:60px 20px;color:#64748b;font-size:18px;font-weight:500}"
".modal{display:none;position:fixed;z-index:1000;left:0;top:0;width:100%;height:100%;"
"background:rgba(0,0,0,0.8);backdrop-filter:blur(4px)}"
".modal.show{display:flex;align-items:center;justify-content:center}"
".modal-content{background:#1e293b;border-radius:16px;max-width:800px;width:90%;"
"max-height:95vh;box-shadow:0 20px 60px rgba(0,0,0,0.6);"
"border:1px solid #334155}"
".modal-content.chart-modal{max-width:900px;max-height:90vh;overflow:hidden}"
".page{display:none;position:fixed;inset:0;z-index:1000;background:#0b1222;"
"color:var(--text);flex-direction:column}"
".page.show{display:flex}"
"body.page-open{overflow:hidden}"
".page-header{padding:16px 20px;border-bottom:1px solid #334155;display:flex;"
"justify-content:space-between;align-items:center;background:linear-gradient(135deg,#152341 0%,#1c2b52 100%)}"
".page-header h2{color:#f1f5f9;font-size:20px;margin:0}"
".page-body{flex:1;overflow-y:auto;padding:16px}"
".modal-header{padding:24px;border-bottom:1px solid #334155;display:flex;"
"justify-content:space-between;align-items:center}"
".modal-header h2{color:#f1f5f9;font-size:24px;margin:0}"
".modal-close{background:none;border:none;font-size:32px;color:#64748b;"
"cursor:pointer;padding:0;width:40px;height:40px;border-radius:8px;"
"transition:all 0.2s}"
".modal-close:hover{background:#334155;color:#f1f5f9}"
".modal-body{padding:24px}"
".discovery-device{background:#0f172a;border:1px solid #334155;border-radius:12px;"
"padding:20px;margin-bottom:12px;display:flex;justify-content:space-between;"
"align-items:center;transition:all 0.2s}"
".discovery-device:hover{border-color:#475569;background:#1a1f2e}"
".discovery-info h3{color:#f1f5f9;font-size:16px;margin-bottom:4px}"
".discovery-info p{color:#64748b;font-size:13px}"
".add-btn{background:#10b981;color:white;border:none;padding:10px 20px;"
"border-radius:8px;cursor:pointer;font-weight:600;transition:all 0.2s}"
".add-btn:hover{background:#059669;transform:translateY(-1px)}"
".add-btn.added{background:#3b82f6}"
".add-btn.added:hover{background:#2563eb}"
".settings-tabs{display:flex;gap:8px;padding:0 24px;border-bottom:1px solid #334155}"
".settings-tab-btn{background:none;border:none;padding:14px 20px;color:#94a3b8;"
"cursor:pointer;font-weight:600;font-size:14px;border-bottom:3px solid transparent;"
"transition:all 0.2s}"
".settings-tab-btn:hover{color:#e2e8f0;background:rgba(255,255,255,0.05)}"
".settings-tab-btn.active{color:#60a5fa;border-bottom-color:#60a5fa}"
".settings-tab-content{display:none;padding:24px}"
".settings-tab-content.active{display:block}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>Temperatures</h1>"
""
"<div style='display:flex;gap:12px;'>"
"<button class='toggle-btn icon-btn' id='scanBtn' onclick='openDiscovery()' title='Discover devices'>🔍</button>"
"<button class='toggle-btn icon-btn' onclick='openSettings()' title='Settings'>⚙️</button>"
"<button class='toggle-btn icon-btn' id='compactViewBtn' onclick='toggleCompactView()' title='Compact / expanded'>⤢</button>"
"</div>"
"</div>"
"<div id='devices'></div>"
"<div id='diagnostics' style='margin:20px auto;max-width:1200px;background:#1e293b;border:1px solid #334155;border-radius:12px;padding:16px;font-size:13px;color:#cbd5e1;'>"
"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;'>"
"<strong style='color:#f1f5f9;'>🩺 Diagnostics</strong>"
"<button onclick='refreshDiagnostics()' style='padding:4px 12px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-size:12px;'>🔄 Refresh</button>"
"</div>"
"<div id='diagnosticsContent' style='display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;'></div>"
"</div>"
"<div class='footer'>"
"<div>Juhku • MIT License</div>"
"<div><a href='https://github.com/juhku1/MijiaESP32Hub' target='_blank'>github.com/juhku1/MijiaESP32Hub</a></div>"
"</div>"
"</div>"
"<div id='discoveryPage' class='page'>"
"<div class='page-header'>"
"<h2>🔍 Discovered devices</h2>"
"<button class='modal-close' onclick='closeDiscovery()'>×</button>"
"</div>"
"<div class='page-body'>"
"<div style='display:flex;justify-content:flex-end;margin-bottom:12px;'>"
"<button class='danger-btn' onclick='clearAllSelections()'>🗑️ Clear all selections</button>"
"</div>"
"<div id='discoveryDevices'></div>"
"</div>"
"</div>"
"<script>"
"let openDeviceSettings=null;"
"let controlTimers={};"
"let activeControlDevice=null;"
"function activateControls(addrClean){"
"const card=document.getElementById('card-'+addrClean);"
"if(!card||!card.classList.contains('compact'))return;"
"if(activeControlDevice&&activeControlDevice!==addrClean){"
"const prevCard=document.getElementById('card-'+activeControlDevice);"
"if(prevCard){prevCard.classList.remove('active-controls');}"
"if(controlTimers[activeControlDevice]){clearTimeout(controlTimers[activeControlDevice]);}"
"}"
"activeControlDevice=addrClean;"
"card.classList.add('active-controls');"
"if(controlTimers[addrClean]){clearTimeout(controlTimers[addrClean]);}"
"controlTimers[addrClean]=setTimeout(()=>{"
"const panel=document.getElementById('settings-'+addrClean);"
"if(panel&&panel.classList.contains('open')){return;}"
"card.classList.remove('active-controls');"
"activeControlDevice=null;"
"},10000);"
"}"
"const compactPref=localStorage.getItem('compactView');"
"let compactView=(compactPref===null)?true:(compactPref==='1');"
"let expandedDevices={};"
"try{expandedDevices=JSON.parse(localStorage.getItem('expandedDevices')||'{}')||{};}catch(e){expandedDevices={};}"
"function applyCompactView(){"
"const btn=document.getElementById('compactViewBtn');"
"if(compactView){document.body.classList.add('compact-view');btn.classList.add('active');}"
"else{document.body.classList.remove('compact-view');btn.classList.remove('active');}"
"localStorage.setItem('compactView',compactView?'1':'0');}"
"function toggleCompactView(){compactView=!compactView;applyCompactView();updateDevices();}"
"function toggleDeviceView(addrClean){"
"expandedDevices[addrClean]=!expandedDevices[addrClean];"
"localStorage.setItem('expandedDevices',JSON.stringify(expandedDevices));"
"updateDevices();}"
"let discoveryInterval=null;"
"async function openDiscovery(){"
"document.getElementById('discoveryPage').classList.add('show');"
"document.body.classList.add('page-open');"
"await startScan();"
"updateDiscoveryDevices();"
"discoveryInterval=setInterval(updateDiscoveryDevices,2000);}"
"async function closeDiscovery(){"
"document.getElementById('discoveryPage').classList.remove('show');"
"document.body.classList.remove('page-open');"
"if(discoveryInterval){clearInterval(discoveryInterval);discoveryInterval=null;}"
"await fetch('/api/stop-scan',{method:'POST'});}"
"async function startScan(){"
"try{"
"const resp=await fetch('/api/start-scan',{method:'POST'});"
"const result=await resp.json();"
"if(!result.ok){"
"alert('Failed to start scan');}"
"}catch(e){alert('Error: '+e.message);}}"
"async function updateDiscoveryDevices(){"
"try{"
"const res=await fetch('/api/devices?all=1');"
"const data=await res.json();"
"const container=document.getElementById('discoveryDevices');"
"if(data.length===0){container.innerHTML='<div class=\"no-devices\">No devices found</div>';return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Unnamed device';"
"const addr=d.addr;"
"const sourceLabel=(d.source&&d.source!==''&&d.source!=='local')?('Satellite '+d.source.replace('satellite-','')):'Master';"
"const isAdded=d.saved;"
"html+='<div class=\"discovery-device\">';"
"html+='<div class=\"discovery-info\">';"
"html+='<h3>'+name+'</h3>';"
"html+='<p>'+addr+' • '+sourceLabel;"
"if(d.hasSensor)html+=' • 🌡️ '+d.temp.toFixed(1)+'°C • 💧 '+d.hum+'%';"
"html+='</p></div>';"
"if(isAdded){"
"html+='<button class=\"add-btn added\" onclick=\"removeFromMain(\\''+addr+'\\');\">✓ Added</button>';"
"}else{"
"html+='<button class=\"add-btn\" onclick=\"addToMain(\\''+addr+'\\');\">+ Add</button>'; }"
"html+='</div>';});"
"container.innerHTML=html;"
"}catch(err){console.error('Error:',err);}}"
"async function addToMain(addr){"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=1'});"
"const result=await resp.json();"
"if(result.ok){"
"updateDiscoveryDevices();"
"updateDevices();"
"}else{alert('Error adding device');}"
"}catch(err){console.error('Error:',err);}}"
"async function removeFromMain(addr){"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=0'});"
"const result=await resp.json();"
"if(result.ok){"
"updateDiscoveryDevices();"
"updateDevices();"
"}else{alert('Error removing device');}"
"}catch(err){console.error('Error:',err);}}"
"async function clearAllSelections(){"
"if(!confirm('Remove all selections from the main view?'))return;"
"try{"
"const resp=await fetch('/api/clear-visibility',{method:'POST'});"
"const result=await resp.json();"
"if(result.ok){"
"updateDiscoveryDevices();"
"updateDevices();"
"}else{alert('Error: failed to clear selections');}"
"}catch(err){console.error('Error:',err);alert('Error: failed to clear selections');}}"
"function toggleSettings(addr){"
"const panel=document.getElementById('settings-'+addr);"
"const card=panel?panel.closest('.device-card'):null;"
"activateControls(addr);"
"if(openDeviceSettings&&openDeviceSettings!==panel){"
"openDeviceSettings.classList.remove('open');"
"const oldCard=openDeviceSettings.closest('.device-card');"
"if(oldCard)oldCard.classList.remove('settings-open');}"
"if(panel){"
"panel.classList.toggle('open');"
"const isOpen=panel.classList.contains('open');"
"openDeviceSettings=isOpen?panel:null;"
"if(card)card.classList.toggle('settings-open',isOpen);}}"
"document.addEventListener('click',(e)=>{"
"if(!e.target.closest('.settings-icon')&&!e.target.closest('.settings-panel')){"
"if(openDeviceSettings){"
"openDeviceSettings.classList.remove('open');"
"const card=openDeviceSettings.closest('.device-card');"
"if(card)card.classList.remove('settings-open');"
"openDeviceSettings=null;}}});"
"async function forgetDevice(addrClean,event){"
"if(event){event.stopPropagation();}"
"if(!confirm('Remove this device? It will be deleted from memory and will reappear if seen again.'))return;"
"console.log('Forgetting device:',addrClean);"
"if(openDeviceSettings){openDeviceSettings.classList.remove('open');openDeviceSettings=null;}"
"try{"
"const resp=await fetch('/api/forget-device?mac='+addrClean,{method:'POST'});"
"const result=await resp.json();"
"console.log('Response:',result);"
"if(result.ok){"
"setTimeout(()=>{updateDevices();updateDiscoveryDevices();},100);"
"}else{"
"alert('Error: '+result.error);"
"}"
"}catch(err){console.error('Error:',err);alert('Error removing device');}}"
"async function saveSettings(addr,addrClean,applyToSimilar,event){"
"if(event){event.stopPropagation();}"
"const name=document.getElementById('name-'+addrClean).value;"
"const showMac=document.getElementById('showmac-'+addrClean).checked?1:0;"
"const showIp=document.getElementById('showip-'+addrClean).checked?1:0;"
"let fieldMask=0;"
"document.querySelectorAll('#settings-'+addrClean+' .field-check').forEach(cb=>{"
"if(cb.checked){fieldMask|=parseInt(cb.getAttribute('data-bit'));}});"
"console.log('Saving:',addr,'name=',name,'showMac=',showMac,'fields=',fieldMask,'apply=',applyToSimilar);"
"try{"
"const resp=await fetch('/api/update-settings',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&name='+encodeURIComponent(name)+'&show_mac='+showMac+'&show_ip='+showIp+'&field_mask='+fieldMask+'&apply_to_similar='+(applyToSimilar?1:0)});"
"const result=await resp.json();"
"console.log('Response:',result);"
"if(result.updated>1){"
"alert('Settings saved for '+result.updated+' devices!');"
"}else{"
"alert('Settings saved!');}"
"if(openDeviceSettings){openDeviceSettings.classList.remove('open');openDeviceSettings=null;}"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Error:',err);alert('Error while saving!');}}"
"async function updateDevices(){"
"if(openDeviceSettings){console.log('Settings open, skipping update');return;}"
"try{"
"const url='/api/devices';"
"const res=await fetch(url);"
"const data=await res.json();"
"cachedDevices=data;"
"console.log('🔄 Updated cachedDevices:',{count:data.length,sample:data.length>0?{name:data[0].name,addr:data[0].addr,visible:data[0].visible,hasSensor:data[0].hasSensor,saved:data[0].saved}:null,allDevices:data.map(d=>({name:d.name,visible:d.visible,hasSensor:d.hasSensor}))});"
"if(data.length===0){document.getElementById('devices').innerHTML="
"'<div class=\"no-devices\">No devices to display</div>';return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Unnamed device';"
"const advName=d.advName||'';"
"const sourceLabel=(d.source&&d.source!==''&&d.source!=='local')?('Satellite '+d.source.replace('satellite-','')):'Master';"
"const addrClean=d.addr.replace(/:/g,'');"
"const isExpanded=!!expandedDevices[addrClean];"
"const useCompact=compactView&&!isExpanded;"
"const savedClass=d.saved?'':'unsaved';"
"html+='<div class=\"device-card '+savedClass+' '+(useCompact?'compact':'')+'\" id=\"card-'+addrClean+'\"'+(useCompact?' data-addr=\"'+addrClean+'\" onclick=\"activateControls(this.dataset.addr)\"':'')+'>'"
"+' <div class=\"device-header\">'"
"+' <div class=\"device-info\">'"
"+' <div class=\"device-name\">';"
"if(!useCompact&&d.source&&d.source!=='local'&&d.source!==''){const satName=d.source.replace('satellite-','');html+='<span style=\"margin-right:6px;\" title=\"Satellite: '+satName+'\">📡</span>';}"
"html+=name;"
"if(useCompact){"
"const age=(typeof d.ageSec==='number')?d.ageSec:0;"
"html+=' <span class=\\\"compact-age\\\">• '+age+'s</span>';"
"}"
"if(!useCompact&&d.showIp&&d.source&&d.source.startsWith('satellite-')){"
"const satIP=d.source.replace('satellite-','');"
"html+=' <span style=\"display:inline-block;margin-left:8px;padding:2px 8px;background:#6366f1;color:white;border-radius:4px;font-size:11px;font-weight:600;vertical-align:middle;\">🛰️ '+satIP+'</span>'; }"
"if(!useCompact&&d.firmware&&d.firmware!=='Unknown'){"
"html+=' <span style=\"display:inline-block;margin-left:8px;padding:2px 8px;background:#3b82f6;color:white;border-radius:4px;font-size:11px;font-weight:600;vertical-align:middle;\">'+d.firmware+'</span>';}"
"html+='</div>';"
"if(d.showMac){"
"html+=' <div class=\"device-mac\">'+d.addr+'</div>';}"
"const age=(typeof d.ageSec==='number')?d.ageSec:0;"
"if(!useCompact){"
"html+=' <div class=\"device-meta\">Source: '+sourceLabel+' • Update: '+age+'s</div>';"
"}"
"html+=' </div>'"
"+' <div class=\"device-header-actions\">';"
"if(d.hasSensor&&(d.fieldMask&1)){"
"html+=' <button onclick=\"openChart(\\''+name.replace(/'/g,\"\\\\'\")+'\\',\\''+d.addr+'\\')\" style=\"padding:6px 10px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-size:18px;line-height:1;\" title=\"Show temperature history\">📊</button>'; }"
"html+=' <button class=\"expand-btn\" onclick=\"toggleDeviceView(\\''+addrClean+'\\')\" title=\"Compact / expanded\">'+(useCompact?'▢':'▣')+'</button>';"
"html+=' <button class=\"settings-icon\" onclick=\"toggleSettings(\\''+addrClean+'\\')\" >⚙️</button>'"
"+' </div>'"
"+' <div class=\"settings-panel\" id=\"settings-'+addrClean+'\">';"
"html+=' <div style=\"padding:14px;\">'"
"+' <label style=\"display:block;margin-bottom:6px;font-weight:600;color:#f1f5f9;font-size:13px;\">Name:</label>'"
"+' <input type=\"text\" id=\"name-'+addrClean+'\" value=\"'+name+'\" style=\"width:100%;padding:8px;margin-bottom:12px;border:1px solid #475569;border-radius:6px;background:#0f172a;color:#e2e8f0;font-size:14px;\" />'"
"+' <label style=\"display:block;margin-bottom:6px;font-weight:600;color:#f1f5f9;font-size:13px;\">Advertised name:</label>'"
"+' <input type=\"text\" value=\"'+advName+'\" readonly style=\"width:100%;padding:8px;margin-bottom:12px;border:1px solid #475569;border-radius:6px;background:#0f172a;color:#94a3b8;font-size:13px;\" />'"
"+' <label style=\"display:flex;align-items:center;margin-bottom:12px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" id=\"showmac-'+addrClean+'\" '+(d.showMac?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">Show MAC address</span>'"
"+' </label>'"
"+' <label style=\"display:flex;align-items:center;margin-bottom:12px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" id=\"showip-'+addrClean+'\" '+(d.showIp?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">Show satellite IP</span>'"
"+' </label>'"
"+' <div style=\"margin-bottom:10px;font-weight:600;color:#f1f5f9;font-size:13px;\">Visible fields:</div>';"
"const fields=[{bit:1,label:'Temperature'},{bit:2,label:'Humidity'},{bit:4,label:'Battery %'},{bit:8,label:'Voltage'},{bit:16,label:'Signal'}];"
"fields.forEach(f=>{"
"const available=(d.availableFields&f.bit)!==0;"
"const checked=(d.fieldMask&f.bit)!==0;"
"if(available){"
"html+=' <label style=\"display:flex;align-items:center;margin-bottom:6px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" class=\"field-check\" data-bit=\"'+f.bit+'\" '+(checked?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">'+f.label+'</span> </label>';}});"
"html+=' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',false,event)\" style=\"width:100%;padding:10px;margin-top:14px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#2563eb\\'\" onmouseout=\"this.style.background=\\'#3b82f6\\'\">💾 Save</button>'"
"+' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',true,event)\" style=\"width:100%;padding:10px;margin-top:6px;background:#10b981;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#059669\\'\" onmouseout=\"this.style.background=\\'#10b981\\'\">🔁 Apply to similar</button>'"
"+' <div class=\"settings-option danger\" onclick=\"forgetDevice(\\''+addrClean+'\\',event)\" style=\"margin-top:10px;background:#dc2626;\">🗑️ Remove device</div>';"
"html+=' </div></div>'"
"+' </div>';"
"if(d.hasSensor&&useCompact){"
"let tempText='--';let tempClass='temp-normal';"
"if((d.fieldMask&1)&&typeof d.temp==='number'){const t=d.temp;tempText=t.toFixed(1)+'°C';if(t<10)tempClass='temp-cold';else if(t<18)tempClass='temp-cool';else if(t>30)tempClass='temp-hot';else if(t>26)tempClass='temp-warm';}"
"let humText='--';if((d.fieldMask&2)&&typeof d.hum==='number'){humText=d.hum+'%';}"
"html+=' <div class=\"compact-row\">'"
"+' <div class=\"compact-item\"><span class=\"compact-label\">Temp</span><span class=\"'+tempClass+'\">'+tempText+'</span></div>'"
"+' <div class=\"compact-item\"><span class=\"compact-label\">Humidity</span><span>'+humText+'</span></div>'"
"+' </div>';"
"}"
"if(d.hasSensor){"
"html+=' <div class=\"sensor-data\">';"
"if((d.fieldMask&1)&&d.temp){"
"let tempClass='temp-normal';"
"if(d.temp<10)tempClass='temp-cold';"
"else if(d.temp<18)tempClass='temp-cool';"
"else if(d.temp>26)tempClass='temp-warm';"
"else if(d.temp>30)tempClass='temp-hot';"
"html+=' <div class=\"sensor-value primary\">'"
"+' <div class=\"sensor-label\">🌡️ Temperature</div>'"
"+' <div class=\"sensor-number '+tempClass+'\">'+d.temp.toFixed(1)+'<span class=\"sensor-unit\">°C</span></div>'"
"+' </div>';}"
"if((d.fieldMask&2)&&d.hum){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">💧 Humidity</div>'"
"+' <div class=\"sensor-number\">'+d.hum+'<span class=\"sensor-unit\">%</span></div>'"
"+' </div>';}"
"if((d.fieldMask&4)&&d.bat){"
"const batClass=d.bat>50?'high':(d.bat>20?'medium':'low');"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">🔋 Battery</div>'"
"+' <div class=\"battery-container\">'"
"+' <div class=\"battery-bar\"><div class=\"battery-fill '+batClass+'\" style=\"width:'+d.bat+'%\"></div></div>'"
"+' <div class=\"sensor-number\" style=\"font-size:18px;\">'+d.bat+'%</div>'"
"+' </div>'"
"+' </div>';}"
"if((d.fieldMask&8)&&d.batMv){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">⚡ Voltage</div>'"
"+' <div class=\"sensor-number\">'+d.batMv+'<span class=\"sensor-unit\">mV</span></div>'"
"+' </div>';}"
"html+=' </div>';}"
"if(d.fieldMask&16){"
"let barCount=0,signalClass='';"
"if(d.rssi>=-50){barCount=4;signalClass='excellent';}"
"else if(d.rssi>=-65){barCount=3;signalClass='good';}"
"else if(d.rssi>=-75){barCount=2;signalClass='fair';}"
"else{barCount=1;signalClass='poor';}"
"html+=' <div class=\"rssi\"><div class=\"signal-container\">'"
"+' <div class=\"signal-bars\">';"
"for(let i=1;i<=4;i++){"
"html+='<div class=\"signal-bar '+(i<=barCount?'active '+signalClass:'inactive')+'\"></div>';}"
"html+=' </div><span style=\"font-size:13px;color:#7f8c8d;\">'+d.rssi+' dBm</span></div></div>';}"
"html+='</div>';});"
"const devicesDiv=document.getElementById('devices');"
"if(devicesDiv.innerHTML!==html){"
"devicesDiv.innerHTML=html;}"
"}catch(error){console.error('Error fetching devices:',error);}}"
"async function refreshDiagnostics(){"
"try{"
"const r=await fetch('/api/diagnostics');"
"const d=await r.json();"
"const uptimeHours=Math.floor(d.uptimeSec/3600);"
"const uptimeMins=Math.floor((d.uptimeSec%3600)/60);"
"const uptimeSecs=d.uptimeSec%60;"
"const resetEmoji=(d.lastReset==='PANIC'||d.lastReset==='INT_WDT'||d.lastReset==='TASK_WDT'||d.lastReset==='WDT')?'⚠️':'✅';"
"const resetColor=(d.lastReset==='PANIC'||d.lastReset==='INT_WDT'||d.lastReset==='TASK_WDT'||d.lastReset==='WDT')?'#ef4444':'#10b981';"
"const memPercent=Math.round((d.freeHeap/327680)*100);"
"document.getElementById('diagnosticsContent').innerHTML="
"'<div><strong>🔄 Boot Count:</strong><br>'+d.bootCount+'</div>'"
"+'<div><strong>'+resetEmoji+' Last Reset:</strong><br><span style=\"color:'+resetColor+'\">'+d.lastReset+'</span></div>'"
"+'<div><strong>⏱️ Uptime:</strong><br>'+uptimeHours+'h '+uptimeMins+'m '+uptimeSecs+'s</div>'"
"+'<div><strong>💾 Free Heap:</strong><br>'+d.freeHeap+' / '+d.minFreeHeap+' bytes ('+memPercent+'%)</div>'"
"+'<div><strong>📦 Largest Block:</strong><br>'+d.largestBlock+' bytes</div>'"
"+'<div><strong>📡 BLE Adverts:</strong><br>'+d.bleAdvCount+' total</div>'"
"+'<div><strong>📱 Devices:</strong><br>'+d.deviceCount+'</div>';"
"}catch(error){console.error('Error fetching diagnostics:',error);}}"
"let currentChart=null;"
"let currentChartName='';"
"let currentChartAddr='';"
"let cachedDevices=[];"
"let touchStartX=0;"
"let touchEndX=0;"
"function getVisibleDevicesWithSensors(){"
"const filtered=cachedDevices.filter(d=>d.saved&&d.hasSensor).sort((a,b)=>a.name.localeCompare(b.name));"
"console.log('📱 getVisibleDevicesWithSensors:',{totalCached:cachedDevices.length,filtered:filtered.length,devices:filtered.map(d=>({name:d.name,addr:d.addr}))});"
"return filtered;}"
"function getCurrentDeviceIndex(){"
"const devices=getVisibleDevicesWithSensors();"
"const idx=devices.findIndex(d=>d.addr===currentChartAddr);"
"console.log('🔍 getCurrentDeviceIndex:',{currentAddr:currentChartAddr,foundIndex:idx});"
"return idx;}"
"function navigateChart(direction){"
"console.log('🔄 navigateChart START:',{direction:direction,currentName:currentChartName,currentAddr:currentChartAddr});"
"const devices=getVisibleDevicesWithSensors();"
"console.log('📊 Devices available:',devices.length);"
"if(devices.length===0){console.warn('⚠️ No devices with sensors');return;}"
"let idx=getCurrentDeviceIndex();"
"console.log('📍 Current index before navigation:',idx);"
"if(idx===-1)idx=0;"
"idx+=direction;"
"console.log('📍 Index after adding direction:',idx);"
"if(idx<0)idx=devices.length-1;"
"if(idx>=devices.length)idx=0;"
"console.log('📍 Final index after wrap:',idx);"
"const device=devices[idx];"
"console.log('✅ Navigating to device:',{name:device.name,addr:device.addr});"
"const hours=parseInt(document.querySelector('.time-btn.active')?.getAttribute('data-hours')||'24');"
"openChart(device.name,device.addr,hours);}"
"function handleChartSwipe(){"
"const diff=touchStartX-touchEndX;"
"console.log('👆 handleChartSwipe:',{startX:touchStartX,endX:touchEndX,diff:diff,threshold:Math.abs(diff)});"
"if(Math.abs(diff)>50){"
"if(diff>0){console.log('➡️ Swipe right - next');navigateChart(1);}"
"else{console.log('⬅️ Swipe left - prev');navigateChart(-1);}}"
"else{console.log('❌ Swipe too small, threshold not met');}}"
"async function openChart(name,addr,hours=24){"
"currentChartName=name;currentChartAddr=addr;"
"document.getElementById('chartModal').classList.add('show');"
"document.querySelectorAll('.time-btn').forEach(b=>b.classList.remove('active'));"
"document.querySelector(`.time-btn[data-hours='${hours}']`)?.classList.add('active');"
"document.getElementById('chartTitle').textContent='📊 '+name;"
"if(currentChart){try{currentChart.destroy();}catch(e){}currentChart=null;}"
"const canvas=document.getElementById('chartCanvas');"
"const ctx=canvas.getContext('2d');"
"try{"
"const r=await fetch('/api/aio/config');"
"const cfg=await r.json();"
"if(!cfg.ok||!cfg.has_key||!cfg.key){alert('Adafruit IO not configured');return;}"
"const macClean=addr.replace(/:/g,'').toLowerCase();"
"const feedName=macClean+'-temp';"
"const url=`https://io.adafruit.com/api/v2/${cfg.username}/feeds/${feedName}/data?start_time=${new Date(Date.now()-hours*3600*1000).toISOString()}`;"
"const res=await fetch(url,{headers:{'X-AIO-Key':cfg.key}});"
"if(!res.ok){alert('No data available');return;}"
"const data=await res.json();"
"const temps=data.reverse().map(d=>({x:new Date(d.created_at),y:parseFloat(d.value)}));"
"const latestEl=document.getElementById('chartLatest');"
"const latest=temps[temps.length-1];"
"if(latestEl){"
"if(latest&&Number.isFinite(latest.y)){"
"const ageMin=Math.max(0,Math.round((Date.now()-latest.x.getTime())/60000));"
"const ageText=ageMin<1?'just now':(ageMin<60?ageMin+' min':Math.round(ageMin/60)+' h');"
"const timeStr=latest.x.toLocaleString(undefined,{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});"
"latestEl.innerHTML=`<span class='label'>Latest</span><span class='value'>${latest.y.toFixed(1)}<span class='unit'>°C</span></span><span class='meta'>${timeStr} • ${ageText} ago</span>`;"
"}else{latestEl.innerHTML=`<span class='label'>Latest</span><span class='value'>--</span>`;}}"
"const tempValues=temps.map(t=>t.y);"
"const avgTemp=tempValues.reduce((a,b)=>a+b,0)/tempValues.length;"
"const minY=Math.floor(avgTemp-10);"
"const maxY=Math.ceil(avgTemp+10);"
"let timeUnit='hour',displayFormat='HH:mm';"
"if(hours<=1){timeUnit='minute';displayFormat='HH:mm';}"
"else if(hours<=24){timeUnit='hour';displayFormat='HH:mm';}"
"else if(hours<=168){timeUnit='day';displayFormat='dd.MM';}"
"else{timeUnit='day';displayFormat='dd.MM';}"
"currentChart=new Chart(ctx,{type:'line',data:{datasets:[{label:'Temperature',data:temps,borderColor:'#3b82f6',backgroundColor:'rgba(59,130,246,0.1)',tension:0.4,fill:true,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{type:'time',time:{unit:timeUnit,displayFormats:{minute:'HH:mm',hour:'HH:mm',day:'dd.MM'}},ticks:{color:'#94a3b8'}},y:{min:minY,max:maxY,ticks:{color:'#94a3b8',stepSize:1,callback:v=>Math.round(v)+'°C'}}}}});"
"canvas.ontouchstart=e=>{touchStartX=e.changedTouches[0].screenX;};"
"canvas.ontouchend=e=>{touchEndX=e.changedTouches[0].screenX;handleChartSwipe();};"
"}catch(e){console.error('Chart error:',e);alert('Error loading data');}}"
"function changeTimeRange(hours){openChart(currentChartName,currentChartAddr,hours);}"
"function closeChart(){document.getElementById('chartModal').classList.remove('show');if(currentChart){currentChart.destroy();currentChart=null;}}"
"async function openSettings(tab='adafruit'){"
"const page=document.getElementById('settingsPage');page.classList.add('show');"
"document.body.classList.add('page-open');"
"switchSettingsTab(tab);"
"if(tab==='adafruit'){"
"try{const r=await fetch('/api/aio/config');"
"if(!r.ok){console.error('Failed to load AIO settings:',r.status);return;}"
"const d=await r.json();"
"if(d.ok){document.getElementById('aioUser').value=d.username||'';"
"document.getElementById('aioEnabled').checked=d.enabled;"
"const types=d.feedTypes||3;"
"document.getElementById('feedTemp').checked=(types&1)!==0;"
"document.getElementById('feedHum').checked=(types&2)!==0;"
"document.getElementById('feedBat').checked=(types&4)!==0;"
"window.oldFeedTypes=types;}}"
"catch(e){console.error('Error loading AIO settings:',e);}}else if(tab==='scan'){"
"try{const r=await fetch('/api/scan-settings');"
"if(!r.ok){console.error('Failed to load scan settings:',r.status);return;}"
"const d=await r.json();"
"if(d.ok){document.getElementById('masterBleEnabled').checked=d.masterBleEnabled;}}"
"catch(e){console.error('Error loading scan settings:',e);}}}"
"function switchSettingsTab(tab){"
"document.querySelectorAll('.settings-tab-btn').forEach(b=>b.classList.remove('active'));"
"document.querySelectorAll('.settings-tab-content').forEach(c=>c.style.display='none');"
"document.querySelector('[data-tab=\"'+tab+'\"]').classList.add('active');"
"document.getElementById('tab-'+tab).style.display='block';}"
"function closeSettings(){document.getElementById('settingsPage').classList.remove('show');document.body.classList.remove('page-open');}"
"async function saveScanSettings(){"
"const enabled=document.getElementById('masterBleEnabled').checked;"
"try{const r=await fetch('/api/scan-settings',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({masterBleEnabled:enabled})});"
"const d=await r.json();if(d.ok){alert('Scan settings saved!');}else{alert('Error: '+d.error);}}"
"catch(e){alert('Error while saving: '+e.message);}}"
"async function saveAioSettings(){"
"const user=document.getElementById('aioUser').value;"
"const key=document.getElementById('aioKey').value;"
"const enabled=document.getElementById('aioEnabled').checked;"
"if(!user||!key){alert('Enter username and key!');return;}"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"const feedTypes=(temp?1:0)|(hum?2:0)|(bat?4:0);"
"try{const r=await fetch('/api/aio/config',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({username:user,key:key,enabled:enabled,feedTypes:feedTypes})});"
"const d=await r.json();if(d.ok){alert('Cloud settings saved!');window.oldFeedTypes=feedTypes;}else{alert('Error: '+d.error);}}"
"catch(e){alert('Error while saving: '+e.message);}}"
"async function sendAioNow(){"
"try{const r=await fetch('/api/aio/send_now',{method:'POST'});"
"const d=await r.json();if(d.ok){alert('Send started! Check Adafruit IO in a few seconds.');}else{alert('Error: '+(d.error||'Unknown'));}}"
"catch(e){alert('Error: '+e.message);}}"
"async function createAioFeeds(){"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"if(!temp&&!hum&&!bat){alert('Select at least one data type first!');return;}"
"const feedTypes=(temp?1:0)|(hum?2:0)|(bat?4:0);"
"const oldTypes=window.oldFeedTypes||0;"
"const removed=oldTypes&(~feedTypes);"
"if(removed!==0){"
"const names=[];"
"if(removed&1)names.push('Temperature');"
"if(removed&2)names.push('Humidity');"
"if(removed&4)names.push('Battery');"
"const msg='⚠️ WARNING!\\n\\nYou are removing these data types:\\n• '+names.join('\\n• ')+'\\n\\nThis DELETES all related feeds and ALL their data permanently!\\n\\nDo you want to continue?';"
"if(!confirm(msg))return;"
"try{"
"const dr=await fetch('/api/aio/delete_feeds?types='+removed,{method:'DELETE'});"
"const dd=await dr.json();"
"if(!dd.ok){alert('Feed deletion failed: '+dd.error);return;}"
"alert('Deleted '+dd.deleted+' feeds');"
"}catch(e){alert('Error while deleting: '+e.message);return;}}"
"try{"
"const user=document.getElementById('aioUser').value;"
"const key=document.getElementById('aioKey').value;"
"if(!user||!key){alert('Enter username and AIO Key in Cloud settings first!');return;}"
"const r2=await fetch('/api/aio/config',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({username:user,key:key,enabled:true,feedTypes:feedTypes})});"
"const d2=await r2.json();"
"if(!d2.ok){alert('Failed to save settings');return;}"
"window.oldFeedTypes=feedTypes;"
"}catch(e){alert('Error: '+e.message);return;}"
"if(!confirm('Create feeds automatically for all visible devices?'))return;"

"try{const r=await fetch('/api/aio/create_feeds',{method:'POST'});"
"const d=await r.json();if(d.ok){alert('✅ Feed creation completed!\\n\\n✓ Created: '+d.created+' new feeds\\n○ Skipped: '+d.existed+' (already exist)\\n✗ Failed: '+d.failed);}else{alert('Error: '+(d.error||'Unknown'));}"
"}catch(e){alert('Error: '+e.message);}}"
"function updateFeedCount(){"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"const types=(temp?1:0)+(hum?1:0)+(bat?1:0);"
"const label=document.getElementById('feedCountEstimate');"
"if(types>0){label.textContent='Estimate: '+(5*types)+' feeds for 5 devices';"
"label.style.color=types<=2?'#10b981':'#f59e0b';}else{label.textContent='Select data types';"
"label.style.color='#94a3b8';}}"
"function openAioHelp(){"
"document.getElementById('aioHelpModal').classList.add('show');}"
"function closeAioHelp(){"
"document.getElementById('aioHelpModal').classList.remove('show');}"
"applyCompactView();"
"setInterval(updateDevices,10000);updateDevices();"
"setInterval(refreshDiagnostics,30000);refreshDiagnostics();"
"</script>"
"<div id='settingsPage' class='page'>"
"<div class='page-header'><h2>⚙️ Settings</h2>"
"<button class='modal-close' onclick='closeSettings()'>×</button></div>"
"<div class='page-body'>"
"<div class='settings-tabs'>"
"<button class='settings-tab-btn active' data-tab='adafruit' onclick='switchSettingsTab(\"adafruit\")'>🟠 Adafruit IO</button>"
"<button class='settings-tab-btn' data-tab='scan' onclick='switchSettingsTab(\"scan\")'>📡 Scan</button>"
"</div>"
"<div id='tab-adafruit' class='settings-tab-content' style='display:block;'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;font-size:14px;color:#cbd5e1;line-height:1.6;'>"
"<strong style='color:#f1f5f9;'>Quick guide:</strong> Create an account at <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;'>io.adafruit.com</a>, copy your Username and AIO Key (🔑), paste them below, select data types, save, and create feeds."
"</div>"
"<div style='margin-bottom:15px;'><label style='display:block;margin-bottom:5px;font-weight:600;'>Username:</label>"
"<input type='text' id='aioUser' placeholder='your_username' style='width:100%;padding:10px;border:1px solid #334155;border-radius:8px;background:#1e293b;color:#e2e8f0;'></div>"
"<div style='margin-bottom:15px;'><label style='display:block;margin-bottom:5px;font-weight:600;'>AIO Key:</label>"
"<input type='password' id='aioKey' placeholder='aio_...' style='width:100%;padding:10px;border:1px solid #334155;border-radius:8px;background:#1e293b;color:#e2e8f0;'></div>"
"<div style='margin-bottom:20px;'><label style='display:flex;align-items:center;gap:10px;'>"
"<input type='checkbox' id='aioEnabled' style='width:20px;height:20px;'><span>Send enabled (every 5 min)</span></label></div>"
"<div style='background:#1e293b;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;'>"
"<h3 style='margin-bottom:12px;font-size:16px;color:#f1f5f9;'>Select data to send:</h3>"
"<div style='background:#7c2d12;border-left:4px solid #f59e0b;padding:12px;border-radius:6px;margin-bottom:12px;'>"
"<p style='margin:0;font-size:13px;color:#fbbf24;line-height:1.5;'><strong>⚠️ Free plan limit:</strong> Max 10 feeds total. Each device + data type = 1 feed. Example: 5 devices × (temp + humidity) = 10 feeds.</p>"
"</div>"
"<div style='display:flex;flex-direction:column;gap:10px;'>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedTemp' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>🌡️ Temperature</span></label>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedHum' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>💧 Humidity</span></label>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedBat' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>🔋 Battery</span></label>"
"</div>"
"<div id='feedCountEstimate' style='margin-top:12px;padding:10px;background:#0f172a;border-radius:8px;font-size:13px;color:#94a3b8;'></div>"
"</div>"
"<button onclick='saveAioSettings()' style='width:100%;padding:12px;background:#10b981;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:10px;'>💾 Save</button>"
"<button onclick='createAioFeeds()' style='width:100%;padding:12px;background:#f59e0b;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:10px;'>🔧 Create feeds automatically</button>"
"<div style='margin:0 0 10px 0;padding:8px;background:#0f172a;border-radius:6px;font-size:12px;color:#94a3b8;border-left:3px solid #10b981;'>ℹ️ Safe to run multiple times - won't overwrite or delete existing feeds</div>"
"<button onclick='sendAioNow()' style='width:100%;padding:12px;background:#3b82f6;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:10px;'>📤 Test send</button>"
"<a href='https://io.adafruit.com' target='_blank' style='display:block;width:100%;padding:10px;background:transparent;color:#94a3b8;border:1px solid #334155;border-radius:8px;font-weight:500;text-align:center;text-decoration:none;margin-bottom:10px;'>🗑️ Manage feeds manually at io.adafruit.com</a>"
"<button onclick='openAioHelp()' style='width:100%;padding:10px;background:transparent;color:#94a3b8;border:1px solid #334155;border-radius:8px;font-weight:500;cursor:pointer;'>📖 Show detailed instructions</button>"
"</div>"
"<div id='tab-scan' class='settings-tab-content'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;font-size:14px;color:#cbd5e1;line-height:1.6;'>"
"<strong style='color:#f1f5f9;'>Scan settings</strong> - Configure how BLE device discovery works."
"</div>"
"<div style='margin-bottom:20px;'>"
"<h3 style='margin-bottom:12px;font-size:16px;color:#f1f5f9;'>Local BLE scan</h3>"
"<label style='display:flex;align-items:center;gap:10px;margin-bottom:10px;'>"
"<input type='checkbox' id='masterBleEnabled' checked style='width:20px;height:20px;'>"
"<span>Use device BLE antenna</span>"
"</label>"
"<div style='padding:12px;background:#0f172a;border-left:3px solid #f59e0b;border-radius:4px;font-size:13px;color:#94a3b8;'>"
"⚠️ If you disable this, the device will rely only on satellite data."
"</div>"
"</div>"
"<button onclick='saveScanSettings()' style='width:100%;padding:12px;background:#10b981;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;'>💾 Save</button>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div id='aioHelpModal' class='modal'><div class='modal-content' style='max-width:700px;'>"
"<div class='modal-header'><h2>📖 Adafruit IO Setup</h2>"
"<button class='modal-close' onclick='closeAioHelp()'>×</button></div>"
"<div style='padding:24px;'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:20px;margin-bottom:20px;'>"
"<h3 style='margin-bottom:15px;color:#f1f5f9;font-size:18px;'>Step-by-step guide</h3>"
"<ol style='margin-left:20px;line-height:2.2;color:#cbd5e1;font-size:15px;'>"
"<li>Create a <strong>free account</strong> at <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;text-decoration:underline;'>io.adafruit.com</a></li>"
"<li>Sign in and click the <strong>yellow key icon (🔑)</strong> in the top-right</li>"
"<li>Copy your <strong>Username</strong> and <strong>AIO Key</strong></li>"
"<li>Return to the ☁️ Cloud popup and paste the values</li>"
"<li>Select the <strong>data types to send</strong> (temp/humidity/battery)</li>"
"<li>Click <strong>\"💾 Save and close\"</strong></li>"
"<li>Open ☁️ Cloud again and click <strong>\"🔧 Create feeds automatically\"</strong></li>"
"<li>Test sending with <strong>\"📤 Test send\"</strong></li>"
"<li>Check <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;text-decoration:underline;'>io.adafruit.com</a> to see the data in your feeds</li>"
"<li>✅ Done! Data is sent automatically every 5 minutes</li>"
"</ol>"
"</div>"
"<div style='background:#1e3a4c;border-left:4px solid #3b82f6;padding:15px;border-radius:8px;margin-bottom:20px;'>"
"<p style='margin:0;font-size:14px;color:#bfdbfe;'><strong>💡 Free plan limits:</strong></p>"
"<ul style='margin:10px 0 0 20px;color:#93c5fd;line-height:1.8;'>"
"<li>Max <strong>10 feeds</strong> total (each device × data type = 1 feed)</li>"
"<li>Examples: <strong>10 devices</strong> with temp only, or <strong>5 devices</strong> with temp + humidity</li>"
"<li>Max <strong>30 messages per minute</strong> (plenty for 5-min intervals)</li>"
"<li><strong>30-day data retention</strong></li>"
"</ul>"
"</div>"
"<button onclick='closeAioHelp()' style='width:100%;padding:12px;background:#6366f1;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;'>✓ OK</button>"
"</div></div></div>"
"<div id='chartModal' class='modal'><div class='modal-content chart-modal'>"
"<div class='modal-header' style='padding:16px 20px;'><h2 id='chartTitle' style='margin:0;font-size:18px;'>📊 Temperature history</h2>"
"<button class='modal-close' onclick='closeChart()'>×</button></div>"
"<div style='padding:16px 20px;'>"
"<div style='display:flex;gap:6px;margin-bottom:12px;'>"
"<button onclick='changeTimeRange(1)' class='time-btn' data-hours='1'>1h</button>"
"<button onclick='changeTimeRange(24)' class='time-btn active' data-hours='24'>24h</button>"
"<button onclick='changeTimeRange(168)' class='time-btn' data-hours='168'>Week</button>"
"<button onclick='changeTimeRange(720)' class='time-btn' data-hours='720'>Month</button>"
"</div>"
"<div id='chartLatest' class='chart-latest'></div>"
"<div style='position:relative;height:calc(90vh - 160px);max-height:500px;min-height:300px;'>"
"<button onclick='navigateChart(-1)' style='position:absolute;left:-10px;top:50%;transform:translateY(-50%);background:#1e293b;border:2px solid #3b82f6;color:#3b82f6;width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:20px;z-index:10;display:flex;align-items:center;justify-content:center;' title='Previous device'>‹</button>"
"<canvas id='chartCanvas'></canvas>"
"<button onclick='navigateChart(1)' style='position:absolute;right:-10px;top:50%;transform:translateY(-50%);background:#1e293b;border:2px solid #3b82f6;color:#3b82f6;width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:20px;z-index:10;display:flex;align-items:center;justify-content:center;' title='Next device'>›</button>"
"</div>"
"</div></div></div>"
"</body>"
"</html>";

#endif // WEBSERVER_H
